
#druid连接池配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://47.98.131.179:3306/blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username: blog
      password: blog
      driver-class-name:
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 1024
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      validation-query: select 1
      query-timeout: 1
#redis



