package com.xsj.blog.dao;

import com.xsj.blog.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    int updateByPrimaryKey(User record);
}