package com.xsj.blog.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.id
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.username
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.password
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.role
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_user
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.id
     *
     * @return the value of b_user.id
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.id
     *
     * @param id the value for b_user.id
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.username
     *
     * @return the value of b_user.username
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.username
     *
     * @param username the value for b_user.username
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.password
     *
     * @return the value of b_user.password
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.password
     *
     * @param password the value for b_user.password
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.role
     *
     * @return the value of b_user.role
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.role
     *
     * @param role the value for b_user.role
     *
     * @mbggenerated Thu Jun 07 14:28:35 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}